name: Deploy to GitHub Pages

on:
  push:
    branches:[main]

job:
  deploy:
    runs-on:ubuntu-latest
    steps:
      name:checkout
      run:actions/checkout@v4

      name:package install
      run:npm install

      name:run server    
      run:npm start
