name: Deploy Node.js App to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify gcloud authentication
        run: gcloud auth list

      - name: Deploy to GCP VM via gcloud SSH
        run: |
          set -e
          gcloud compute ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_VM_NAME }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --command="
              set -e
              APP_DIR=/home/${{ secrets.GCP_USER }}/ConvoBot

              # Prepare directory
              mkdir -p \$APP_DIR

              # If repo exists, update; otherwise clone
              if [ -d \"\$APP_DIR/.git\" ]; then
                cd \$APP_DIR
                git pull origin main
              else
                git clone https://github.com/CHINMAYHACKERHACKER/ConvoPilot.git \$APP_DIR
                cd \$APP_DIR
              fi

              npm install --production
              pm2 restart ConvoBot || pm2 start src/server.js --name ConvoBot
              pm2 save
            "
